version: '3.8'

services:
  flask-app:
    build:
      context: /home/lucasburgos/Public/Work/FLASK-NEXT-CONTAINER
      dockerfile: flask-app/Dockerfile 
    volumes:
      - ./flask-app:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development

