version: '3.8'

services:
  flask:
    build: ./flask-app
    volumes:
      - ./flask-app:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  nextjs:
    build: ./nextjs-app
    volumes:
      - ./nextjs-app:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://flask:5000  # Flask API URL
    depends_on:
      - flask
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

